Repository jashkenas/backbone, pull requests merged in 2023-07, with the labels that each got.

#4267 Comment about combined defaults and extend
  backbone.js
Labels: documentation

#4240 #3391 - Match trailing slash on root to how root was configured.
  backbone.js
  index.html
  test/router.js
Labels: enhancement

#4272 Add a .editorconfig; prepare for switching to 4-space indentation
  .editorconfig
Labels: quality

#4277 Security policy
  README.md
  SECURITY.md
Labels: enhancement, documentation, quality

#4174 Fixes #4097, add parse option to docs section for Backbone.Collection
  index.html
Labels: documentation

#4276 Code of conduct
  CODE_OF_CONDUCT.md
  README.md
Labels: enhancement, documentation
